version: '3.8'

services:
  flask_app:
    image: galfrylich/sigmabit-task:26
    container_name: flask_app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
    networks:
      - app-network

  nginx-proxy:
    image: galfrylich/nginx-proxy:26
    container_name: nginx-proxy
    ports:
      - "8081:80"
    depends_on:
      - flask_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
